spring.application.name=event-service

spring.datasource.url=jdbc:postgresql://localhost:5432/eventpulse
spring.datasource.username=postgres
spring.datasource.password=admin123

spring.jpa.hibernate.ddl-auto=update